import { Command } from "commander";
import { CcnaAdapter } from "@/adapters/ccna-adapter";
import { REPO_NAME, REPO_URL } from "@/constants";

const program = new Command();
program
  .name("testownik-converter")
  .description(
    "A command-line converter of quizzes into KN Solvro's Testownik format.",
  )
  .option("-t, --title <string>", "quiz title", "Testownik Quiz")
  .option(
    "-d, --description <string>",
    "quiz description",
    `Generated by ${REPO_NAME}: ${REPO_URL}`,
  )
  .option("-o, --output <filename>", "output JSON filename", "testownik.json")
  .version("1.0.0");

program
  .command("ccna")
  .argument("<filename>", "input text filename")
  .description("Parses questions from Cisco's CCNA exam format.")
  .action((inputFilename: string) => {
    const options = program.opts();

    const outputFilename: string = options.output;
    const quizTitle: string = options.title;
    const quizDescription: string | undefined = options.description;

    const adapter = new CcnaAdapter({
      inputFilename,
      outputFilename,
      quizTitle,
      quizDescription,
    });

    adapter.writeOutput();
    console.log(`Quiz written to ${options.output}!`);
  });

program.parse(process.argv);
