import { Command } from "commander";

import { CcnaAdapter } from "@/adapters/ccna-adapter";
import { REPO_NAME, REPO_URL, VERSION } from "@/constants";
import { cardIntro, cardOutro, cardError, logger } from "@/logging";

const program = new Command();
program
  .name("testownik-converter")
  .description(
    "A command-line converter of quizzes into KN Solvro's Testownik format.",
  )
  .option("-t, --title <string>", "quiz title", "Testownik Quiz")
  .option(
    "-d, --description <string>",
    "quiz description",
    `Generated by ${REPO_NAME}: ${REPO_URL}`,
  )
  .option("-o, --output <filename>", "output JSON filename", "testownik.json")
  .version(VERSION);

program
  .command("ccna")
  .argument("<filename>", "input text filename")
  .description("Parses questions from Cisco's CCNA exam format.")
  .action((inputFilename: string) => {
    logger.print(cardIntro);
    try {
      const options = program.opts();

      const outputFilename: string = options.output;
      const quizTitle: string = options.title;
      const quizDescription: string | undefined = options.description;

      const adapter = new CcnaAdapter({
        inputFilename,
        outputFilename,
        quizTitle,
        quizDescription,
      });

      adapter.writeOutput();

      logger.print(cardOutro);
    } catch (error) {
      logger.error(
        error instanceof Error ? error.message : `Unknown error: ${error}`,
      );
      logger.print(cardError);
      process.exitCode = 1;
    }
  });

program.parse(process.argv);
